### ISSUE TITLE
Pelican-toc doesn't work with 3.7.0

### ISSUE THREAD

**Issue by sprnza** [getpelican/pelican-plugins#847]
With
```
PLUGINS = ['pelican-toc']
```
in pelicanconf.py, it returns:
```
CRITICAL: AttributeError: module 'pelican-toc' has no attribute 'register'
```

**Comment by ingwinlu** [comment]
no idea how you managed to get that error. it certainly has a register function.

works for me on all recent pelican versions.

**Comment by justinmayer** [comment]
@sprnza: Please let us know if you need further assistance. Better yet, please find us on the [#pelican channel](http://docs.getpelican.com/en/stable/contribute.html#the-pelican-irc-channel). 😄
