### ISSUE TITLE
Fix i18N_subsites tests

### ISSUE THREAD

**Issue by oulenz** [getpelican/pelican-plugins#1089]
Given that `i18N_subsites` seems to be a popular plugin, we should get `test_i18n_subsites.py` working so we can actually test compatibility with different versions of Pelican. The problem is that the tests were only ever designed to work with Pelican 3.4. To quote [the commit](https://github.com/getpelican/pelican-plugins/commit/fc71eeb6faa23f8e6e28ebff55769473130c3917):
> the test suite works only with pelican 3.4, later versions add a timezone field to the date

Concretely, I am running into the following issues:
* with older versions of Pelican (3.4.0 -- 3.6.0) I get `AttributeError: 'Environment' object has no attribute 'install_gettext_translations'` on line 305.
* with newer versions of Pelican (3.6.2 -- 3.7.1), `from pelican.tests.support import get_settings` results in a `ModuleNotFoundError`, since `pelican.tests` is no longer exposed since 3.6.2 (due to [this commit](https://github.com/getpelican/pelican/commit/bd5dfa0b3ec9560a1a453907f9f3767b9b89ea01)). This problem does not occur if Pelican is directly installed directly from code, so we can run the tests against the current version of Pelican, but it makes testing of compatibility with older versions of Pelican unpractical.
* with the current master of Pelican (and after applying https://github.com/getpelican/pelican-plugins/pull/1088), the last test fails on line 138 due to the produced output. This may be due to the timezone field mentioned above, or because of other changes to Pelican since 3.4.

@smartass101

**Comment by Lucas-C** [comment]
The tests should be fixed by https://github.com/getpelican/pelican-plugins/pull/1174
