### ISSUE TITLE
i18n_subsite broken by pelican pull request https://github.com/getpelican/pelican/pull/2128

### ISSUE THREAD

**Issue by 3e4** [getpelican/pelican-plugins#937]
https://github.com/getpelican/pelican/pull/2128

Commit https://github.com/getpelican/pelican/commit/089b46b7eb86cb55491d3c8e8bccb956b6dceeff removed Draft class from pelican/contents.py. As a consequence, loading i18n_subsites failes

    ERROR: Cannot load plugin `i18n_subsites`
    | ImportError: cannot import name 'Draft'

**Comment by Lucas-C** [comment]
Already mentioned by [@ashwinvis](https://github.com/getpelican/pelican-plugins/pull/953#issuecomment-368568505), but this also affects the `representative_image` plugin

**Comment by 3e4** [comment]
This issue is fixed in version 3.7.1. Closing.

**Comment by jorgesumle** [comment]
So, you downgraded Pelican in order to solve the issue?

**Comment by ybazlov** [comment]
After upgrading to pelican 4.0.0, loading i18n_subsites fails again, with the same error 
```
ERROR: Cannot load plugin `i18n_subsites`
| ImportError: cannot import name 'Draft'
```
Workaround: downgrade to pelican 3.7.1.

**Comment by siongui** [comment]
Same issue after upgrading to 4.0.0 as @ybazlov

**Comment by justinmayer** [comment]
@siongui: Fixed by #1084

**Comment by stepcellwolf** [comment]
The issue still exists in pelican-4.0.1 version, if you want to solve the issue, please downgrade with following command: pip install pelican==3.7.1

**Comment by avaris** [comment]
@stepcellwolf did you update the plugin? Latest version shouldn't throw this error.

**Comment by stepcellwolf** [comment]
@avaris after manual updating the plugin the error is gone. Thanks a lot.
